<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="17" passed="13" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-18T11:46:44 EDT" name="My Fork" finished-at="2023-09-18T11:48:09 EDT" duration-ms="84698">
    <groups>
    </groups>
    <test started-at="2023-09-18T11:46:44 EDT" name="Regression" finished-at="2023-09-18T11:47:29 EDT" duration-ms="45089">
      <class name="testcases.DropdownTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.DropdownTest@50b472aa]" started-at="2023-09-18T11:47:25 EDT" name="setUp" finished-at="2023-09-18T11:47:26 EDT" duration-ms="836" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="dropdown()[pri:0, instance:testcases.DropdownTest@50b472aa]" started-at="2023-09-18T11:47:26 EDT" name="dropdown" finished-at="2023-09-18T11:47:29 EDT" duration-ms="2870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dropdown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.DropdownTest@50b472aa]" started-at="2023-09-18T11:47:29 EDT" name="tearDown" finished-at="2023-09-18T11:47:29 EDT" duration-ms="114" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.DropdownTest -->
      <class name="testcases.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:44 EDT" name="setUp" finished-at="2023-09-18T11:46:46 EDT" duration-ms="1663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="enterInvalidEmailLogin()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:46 EDT" name="enterInvalidEmailLogin" finished-at="2023-09-18T11:46:49 EDT" duration-ms="3753" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterInvalidEmailLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:49 EDT" name="tearDown" finished-at="2023-09-18T11:46:49 EDT" duration-ms="140" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:49 EDT" name="setUp" finished-at="2023-09-18T11:46:50 EDT" duration-ms="779" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="openCourseGallery()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:50 EDT" name="openCourseGallery" finished-at="2023-09-18T11:46:53 EDT" duration-ms="2653" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Choose your area of expertise] but found [Business Analyst]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Choose your area of expertise] but found [Business Analyst]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pageobject.CourseGalleryPage.hardAsserts(CourseGalleryPage.java:41)
at testcases.LoginTest.openCourseGallery(LoginTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openCourseGallery -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:53 EDT" name="tearDown" finished-at="2023-09-18T11:46:53 EDT" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:53 EDT" name="setUp" finished-at="2023-09-18T11:46:54 EDT" duration-ms="851" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="openSignInPage()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:54 EDT" name="openSignInPage" finished-at="2023-09-18T11:46:56 EDT" duration-ms="2396" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openSignInPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:56 EDT" name="tearDown" finished-at="2023-09-18T11:46:56 EDT" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:56 EDT" name="setUp" finished-at="2023-09-18T11:46:57 EDT" duration-ms="823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="openSignUpPage()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:46:57 EDT" name="openSignUpPage" finished-at="2023-09-18T11:47:00 EDT" duration-ms="3045" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Already have] but found [Already have an account? Log In],
expected [8] but found [14],
expected [Email address] but found [Email]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Already have] but found [Already have an account? Log In],
expected [8] but found [14],
expected [Email address] but found [Email]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at pageobject.SignUpPage.softAsserts(SignUpPage.java:60)
at testcases.LoginTest.openSignUpPage(LoginTest.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openSignUpPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:00 EDT" name="tearDown" finished-at="2023-09-18T11:47:00 EDT" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:00 EDT" name="setUp" finished-at="2023-09-18T11:47:01 EDT" duration-ms="880" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="startDriver()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:01 EDT" name="startDriver" finished-at="2023-09-18T11:47:03 EDT" duration-ms="1865" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:03 EDT" name="tearDown" finished-at="2023-09-18T11:47:03 EDT" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:03 EDT" name="setUp" finished-at="2023-09-18T11:47:04 EDT" duration-ms="851" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateCheckBox()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:04 EDT" name="validateCheckBox" finished-at="2023-09-18T11:47:07 EDT" duration-ms="2982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCheckBox -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:07 EDT" name="tearDown" finished-at="2023-09-18T11:47:07 EDT" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:07 EDT" name="setUp" finished-at="2023-09-18T11:47:08 EDT" duration-ms="829" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateEmailPasswordLogin()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:08 EDT" name="validateEmailPasswordLogin" finished-at="2023-09-18T11:47:15 EDT" duration-ms="7291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEmailPasswordLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:15 EDT" name="tearDown" finished-at="2023-09-18T11:47:16 EDT" duration-ms="147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:16 EDT" name="setUp" finished-at="2023-09-18T11:47:16 EDT" duration-ms="774" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateError()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:16 EDT" name="validateError" finished-at="2023-09-18T11:47:25 EDT" duration-ms="8628" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@4a22f9e2]" started-at="2023-09-18T11:47:25 EDT" name="tearDown" finished-at="2023-09-18T11:47:25 EDT" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Regression -->
    <test started-at="2023-09-18T11:47:29 EDT" name="Smoke" finished-at="2023-09-18T11:48:09 EDT" duration-ms="39493">
      <class name="testcases.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:29 EDT" name="setUp" finished-at="2023-09-18T11:47:30 EDT" duration-ms="846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="enterInvalidEmailLogin()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:30 EDT" name="enterInvalidEmailLogin" finished-at="2023-09-18T11:47:34 EDT" duration-ms="4397" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterInvalidEmailLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:34 EDT" name="tearDown" finished-at="2023-09-18T11:47:34 EDT" duration-ms="137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:34 EDT" name="setUp" finished-at="2023-09-18T11:47:35 EDT" duration-ms="794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="openCourseGallery()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:35 EDT" name="openCourseGallery" finished-at="2023-09-18T11:47:41 EDT" duration-ms="6181" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Choose your area of expertise] but found [Business Analyst]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Choose your area of expertise] but found [Business Analyst]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pageobject.CourseGalleryPage.hardAsserts(CourseGalleryPage.java:41)
at testcases.LoginTest.openCourseGallery(LoginTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openCourseGallery -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:41 EDT" name="tearDown" finished-at="2023-09-18T11:47:42 EDT" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:42 EDT" name="setUp" finished-at="2023-09-18T11:47:42 EDT" duration-ms="823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="openSignInPage()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:42 EDT" name="openSignInPage" finished-at="2023-09-18T11:47:45 EDT" duration-ms="2548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openSignInPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:45 EDT" name="tearDown" finished-at="2023-09-18T11:47:45 EDT" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:45 EDT" name="setUp" finished-at="2023-09-18T11:47:46 EDT" duration-ms="761" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="openSignUpPage()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:46 EDT" name="openSignUpPage" finished-at="2023-09-18T11:47:49 EDT" duration-ms="2807" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Already have] but found [Already have an account? Log In],
expected [8] but found [14],
expected [Email address] but found [Email]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Already have] but found [Already have an account? Log In],
expected [8] but found [14],
expected [Email address] but found [Email]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at pageobject.SignUpPage.softAsserts(SignUpPage.java:60)
at testcases.LoginTest.openSignUpPage(LoginTest.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openSignUpPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:49 EDT" name="tearDown" finished-at="2023-09-18T11:47:49 EDT" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:49 EDT" name="setUp" finished-at="2023-09-18T11:47:50 EDT" duration-ms="794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="startDriver()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:50 EDT" name="startDriver" finished-at="2023-09-18T11:47:52 EDT" duration-ms="1946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:52 EDT" name="tearDown" finished-at="2023-09-18T11:47:52 EDT" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:52 EDT" name="setUp" finished-at="2023-09-18T11:47:53 EDT" duration-ms="849" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateCheckBox()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:53 EDT" name="validateCheckBox" finished-at="2023-09-18T11:47:55 EDT" duration-ms="2909" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCheckBox -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:55 EDT" name="tearDown" finished-at="2023-09-18T11:47:56 EDT" duration-ms="125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:56 EDT" name="setUp" finished-at="2023-09-18T11:47:56 EDT" duration-ms="837" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateEmailPasswordLogin()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:47:56 EDT" name="validateEmailPasswordLogin" finished-at="2023-09-18T11:48:00 EDT" duration-ms="3157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEmailPasswordLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:48:00 EDT" name="tearDown" finished-at="2023-09-18T11:48:00 EDT" duration-ms="120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:48:00 EDT" name="setUp" finished-at="2023-09-18T11:48:00 EDT" duration-ms="772" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateError()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:48:00 EDT" name="validateError" finished-at="2023-09-18T11:48:08 EDT" duration-ms="7966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@56620197]" started-at="2023-09-18T11:48:08 EDT" name="tearDown" finished-at="2023-09-18T11:48:09 EDT" duration-ms="148" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Smoke -->
  </suite> <!-- My Fork -->
</testng-results>
